#
# Module manifest for module 'cDockerBinaries'
#
# Generated by: Matt Sollie
#
# Generated on: 6/29/2017
#

@{

RootModule = 'cDSCDockerSwarm.psm1'
ModuleVersion = '0.9.2'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = '692cae80-eb9f-461a-93ea-c44aed79cc4c'

Author = 'Matt Sollie'
Copyright = '(c) 2017 matt sollie. All rights reserved.'
Description = 'DSC Module for Docker and Swarm management'

# DSC resources to export from this module
DscResourcesToExport = @('cDockerConfig','cDockerSwarm')

}

